# Attachment storage options

# For now there's only a single option for attachment storage
type="gridstore"
bucket="attachments"

# If true then decodes base64 encoded attachments to binary before storing to DB.
# Decoding base64 attachments expects consistent line length and default base64 alphabet
decodeBase64=true
