# If enabled then WildDuck exposes a limited POP3 interface for listing and fetching emails
enabled=false
port=9995
# by default bind to localhost only
host="0.0.0.0"

# Use `true` for port 995 and `false` for 110
secure=true

# If true, then do not show server info in CAPA response
disableVersionString=false

# How many latest messages to list for LIST and UIDL
# POP3 server never lists all messages but only a limited length list
maxMessages=250

# Max donwload bandwith per day in megabytes
maxDownloadMB=10000

# If true, then expect HAProxy PROXY header as the first line of data
useProxy=false

# an array of IP addresses to ignore (not logged)
ignoredHosts=[]

#name="WildDuck POP3"
#version="1.0.0"

[tls]
# If certificate path is not defined, use global or built-in self-signed certs
#key="/path/to/server/key.pem"
#cert="/path/to/server/cert.pem"

[setup]
# Public configuration for POP3
hostname="0.0.0.0"
secure=true
# port defaults to pop3.port
#port=9995
